### ISSUE TITLE
Error while deleting room

### ISSUE THREAD

**Issue by getupandgo** [LuxoftLab/ShareClipboard#10]
When I create a room and immediately delete it, this error occurs:
ASSERT failure in QList<T>::operator[]: "index out of range", file ../../../Qt5.3.2/5.3/gcc/include/QtCore/qlist.h, line 487

P.S.
I think bug is in the onListItemChaned() slot in line 
ui->listWidget->selectedItems()[0]->text() == localServer
Check it!

**Comment by vikmaksimenko** [comment]
Bug fixed. I simplified buttons code and now it's correct. Please, check it
