### ISSUE TITLE
Get valid ip adress of the server to automatically join room on server create

### ISSUE THREAD

**Issue by getupandgo** [LuxoftLab/ShareClipboard#14]
Controller and ServerRoom has'nt valid local ip. (The method getAddr returns loopback, i.e. 127.0.0.1). That's why server can't autoconnect to room, which was just created by himself.

**Comment by vikmaksimenko** [comment]
Tried to fix it on "vikmaksimenko" branch. Please verify the correctness

**Comment by Asalle** [comment]
Weird, it can connect at interfaces branch.

**Comment by getupandgo** [comment]
Yep, with some corrections this will work.
