### ISSUE TITLE
Discuss and approve code style guide 

### ISSUE THREAD

**Issue by vikmaksimenko** [LuxoftLab/ShareClipboard#16]
Colleagues, I propose to create and approve a code style guide for our project. It will simplify the understanding of code and it's further integration. I think we can use http://google-styleguide.googlecode.com/svn/trunk/cppguide.html  or http://qt-project.org/wiki/Qt_Coding_Style as guide (or both of them).
BUT after approval we should refactor our code according to guide and keep writing code according to it

@gorz ,  @Asalle ,  @lrepno and @getupandgo , please comment this proposal

**Comment by Asalle** [comment]
I guess it's an excellent idea. Totally agree.

**Comment by getupandgo** [comment]
Check our Wiki.
P.S. Someone, format code in samples, i just don't know how to do it :C

**Comment by Asalle** [comment]
I think, that this 
>Public classes start with a ‘Q’ (QRgb) followed by an upper case letter. Public functions most often start with a ‘q’ (qRgb).

is really not necessary.
(taken from Wiki)
