### ISSUE TITLE
write the ClipboardService class

### ISSUE THREAD

**Issue by vikmaksimenko** [LuxoftLab/ShareClipboard#2]
write the ClipboardService class  that will provide the realization of copy/paste functions

**Comment by lrepno** [comment]
ClipboardService class created in https://github.com/LuxoftLab/ShareClipboard/commit/08c7e5f225ab980d1d2279b4e32335f42eb026d3

**Comment by vikmaksimenko** [comment]
I refactored it in 70d9bba for sending signals on text, images and files

**Comment by vikmaksimenko** [comment]
More or less it's implemented. The next part of ClipboardService improvement is #17
