### ISSUE TITLE
QIcon solution.

### ISSUE THREAD

**Issue by lrepno** [LuxoftLab/ShareClipboard#22]
As you may know there are troubles with minimized desktop application and (as for me) Icon doesn't appear.
I have tried to make a direct path in QIcon constructor but it didn't help. 

So if you have any ideas to fix it would be really nice.

**Comment by Asalle** [comment]
I guess, you just forgot to add a slash to the icon file path. I added a more colorful icon too, if you didn't see a dark icon on a dark background (as I did).  
Commit:https://github.com/LuxoftLab/ShareClipboard/commit/c012d519ae32e3578218d6904bdc70c5a54624d9

Also, if you use Ubuntu 14.04, you will experience this bug(https://bugreports.qt.io/browse/QTBUG-31762), i. e. icon on the left-top area, and not where it's supposed to be.
