### ISSUE TITLE
Fix bug when adding rooms with the same names

### ISSUE THREAD

**Issue by Asalle** [LuxoftLab/ShareClipboard#23]
Let's assume that we have 2 PCs: A and B.
A creates room "1" and becomes a sever. B connects to 1.
Then B creates room "1" and becomes a server in entirely different room. A connects to B's 1.
Then, two valid networks named "1" are displayed in the room list widget of both PCs.

So, let's summarize: if the same pc **_can_** be a client in one network and a server in another, how do we handle problems like this? (Because so far we catch an exception and quit :( )

**Comment by vikmaksimenko** [comment]
I think same device can't be a server an a host at same time, but as far ar I can remember we can have with same name
